name: Run Bundler Audit

on:
  pull_request:

jobs:
  run-bundler_audit:
    name: Run bundler audit
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: "3.0"
        - name: Install bundle audit
          run: gem install bundle-audit
        - name: Update Ruby Advisory Database
          run: bundle-audit update
        - name: Run audit
          run: bundle audit
          