name: Run RSpec tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  APPLICATION_NAME: eventboss

jobs:
  run-tests:
    name: Run RSpec
    runs-on: [self-hosted, utils]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 158094083467

      - name: Set up Docker Context for Buildx
        id: buildx-context
        shell: bash
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Build tests image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-test
          tags: ${{ env.APPLICATION_NAME }}:rspec-tests-${{ github.sha }}
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        shell: bash
        run: |
          docker run --rm \
            -e "RAILS_ENV=test" \
            -t ${{ env.APPLICATION_NAME }}:rspec-tests-${{ github.sha }} "bundle exec rspec"
            